import {
  pgTable,
  varchar,
  pgEnum,
  uuid,
  timestamp,
  text,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

export const statusEnum = pgEnum("status", [
  "NEW",
  "IN_PROGRESS",
  "COMPLETED",
  "ARCHIVED",
  "TERMINATED",
]);

export const timestamps = {
  createdAt: timestamp().notNull().defaultNow(),
  updatedAt: timestamp(),
  archivedAt: timestamp(),
};

export const users = pgTable("projects", {
  // autogenerated UID
  uid: uuid(),
  // required project name
  name: varchar({ length: 64 }).notNull().unique(),
  // tag list, defaults to empty list
  // https://orm.drizzle.team/docs/guides/empty-array-default-value#postgresql
  tags: text("tags")
    .array()
    .notNull()
    .default(sql`'{}'::text[]`),
  // required project description
  description: varchar({ length: 256 }).notNull(),
  status: statusEnum().default("NEW").notNull(),
  ...timestamps,
});
